version: '3.1'

volumes:
  pg_project:

services:
  pg_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5439:5432

  web:
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./:/docker/
    depends_on:
      - pg_database
    ports:
      - 8000:8000