# Generated by Django 3.2.6 on 2021-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210812_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer of User', 'verbose_name_plural': 'Answers of User'},
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.CharField(default=None, max_length=100, verbose_name='Результаты'),
        ),
    ]
